name: psychphinder
description: A searcher for the TV show Psych.
publish_to: 'none'
version: 1.1.4+17

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  fuzzywuzzy: ^1.1.6
  flutter_list_view: ^1.1.21
  hive_ce: ^2.8.0+3
  hive_ce_flutter: ^2.2.0
  provider: ^6.0.5
  file_picker: ^8.0.7
  shared_preferences: ^2.2.0
  flutter_donation_buttons: ^0.4.10
  check_app_version: ^2.0.0
  url_launcher: ^6.1.12
  widgets_to_image: ^1.0.0
  share_plus: ^10.0.0
  fluttertoast: ^8.2.4
  wallpaper_handler: ^0.0.2
  gal: ^2.3.0
  google_nav_bar: ^5.0.6
  diacritic: ^0.1.4
  highlight_text: ^1.7.0
  number_to_words_english: ^2.0.2
  font_awesome_flutter: ^10.5.0
  flutter_markdown: ^0.7.3
  package_info_plus: ^8.0.2
  file_saver: ^0.2.8
  universal_html: ^2.2.4
  go_router: ^14.2.3
  app_links: ^6.2.0
  flutter_colorpicker: ^1.0.3
  sheet: ^1.0.0

dev_dependencies:
  hive_ce_generator: ^1.8.1
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
    image_path: "assets/icon/icon-1024x1024.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon-1024x1024.png"
  web:
    generate: true
    image_path: "assets/icon/icon-1024x1024.png"

flutter:
  fonts:
    - family: PsychFont
      fonts:
        - asset: fonts/PsychFont-Regular.ttf
        - asset: fonts/PsychFont-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato/Lato-Italic.ttf
          style: italic

  uses-material-design: true

  assets:
    - assets/data.csv
    - assets/episodes.csv
    - assets/references.csv
    - assets/CHANGELOG.md
    - assets/background/