// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:psychphinder/classes/phrase_class.dart';
import 'package:psychphinder/classes/profile_class.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PhraseAdapter());
    registerAdapter(ProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PhraseAdapter());
    registerAdapter(ProfileAdapter());
  }
}
